### ISSUE TITLE
Connection lost with subscribe_states

### ISSUE THREAD

**Issue by roger-** [esphome/aioesphomeapi#140]
My device is a bit unstable and subscribe_states() does not seem to reconnect automatically. Can I use ReconnectLogic or something?

**Comment by jesserockz** [comment]
Yes that is what it is for.

**Comment by roger-** [comment]
Any sample code?

**Comment by jesserockz** [comment]
Not exactly, but HAs code uses it: https://github.com/home-assistant/core/blob/dev/homeassistant/components/esphome/__init__.py#L299
