### ISSUE TITLE
device_class for TextSensor ?

### ISSUE THREAD

**Issue by jkerdreux-imt** [esphome/aioesphomeapi#183]
I'm using device_class to find the device type associated to an Entity. For example, device_class=='power', it's a power-meter. This is for SensorInfo, but some component in ESPHome only support TextSensor. This is the case in example for the ble_scanner. This sounds good because it returns a JSON string, but as TextSensorInfo doesn't provide device_class, I'm unable to find if this is ble_scanner or any other TextSensor component. 

Is there a way to fix this (without having to hardcode this information in another field like the name for example) ?

Best regards.

**Comment by jesserockz** [comment]
Please create (or find existing) a request in https://github.com/esphome/feature-requests

TextSensors do not currently support `device_class`, there is no limitation to this, it is just not in the code and someone needs to add it.
