### ISSUE TITLE
media_player only supports subset of HA's media_player capabilities

### ISSUE THREAD

**Issue by paco3346** [esphome/aioesphomeapi#285]
Features such as on/off, selecting source, and all statuses aren't part of the esphome API.

**Comment by paco3346** [comment]
I'm working on a PR for this. Mostly made this issue as a placeholder to inform others it's being worked on.

**Comment by bdraco** [comment]
I'm going to close this issue since its been more than 6 months. We would still be happy to get a PR to improve the media player, but we don't need an issue for it 👍
