### ISSUE TITLE
Timeout in send_message_await_response_complex too short?

### ISSUE THREAD

**Issue by virtualm2000** [esphome/aioesphomeapi#286]
Could the timeout timeout: float = 10.0, in send_message_await_response_complex be the too short for ble response? Sometimes it takes a while to read the services and characteristics.

Thank you!

**Comment by bdraco** [comment]
Related issue https://github.com/home-assistant/core/issues/80125

**Comment by bdraco** [comment]
Most of the BLE timeouts are too short
