### ISSUE TITLE
esphome on a separate network?

### ISSUE THREAD

**Issue by MagicJF** [esphome/aioesphomeapi#375]
Hi!
Can interactions be done from outside the local area network?
I want to control an esp device that is not under the same LAN as my  home assistant, not sure if this library might allow that.

Thanks 

Edit:  This description make me think is possible but I would appreciate an example/confirmation
![imagen](https://user-images.githubusercontent.com/92638213/216766685-385038ab-173c-479e-a88d-d463ca366a76.png)

Edit2: just found that on Oct 2019 was not possible, wondering if are there any updates.
https://github.com/esphome/feature-requests/issues/441

**Comment by ssieb** [comment]
As long as you can connect to the device, it will work.  You obviously won't be able to use mdns lookup, but you can use the IP address.
