### ISSUE TITLE
Encryption instead of password

### ISSUE THREAD

**Issue by klein1jo** [esphome/aioesphomeapi#414]
I have the native API enabled using encryption and key instead of password.  The example shows connecting using password for aioesphomeapi.  Do you have an example use encryption and key or can this not be done with aioesphomeapi?

**Comment by ssieb** [comment]
HA uses this library and it's kept up to date with any changes in esphome, so yes, you can do that.  I don't have an example though.

**Comment by klein1jo** [comment]
For encryption:

cli = aioesphomeapi.APIClient("api_test.local", 6053, None, noise_psk="MyKey")
