### ISSUE TITLE
LOG_LEVEL_CONFIG is missed; LOG_LEVEL_DEBUG, LOG_LEVEL_VERBOSE and LOG_LEVEL_VERY_VERBOSE are reduced by 1

### ISSUE THREAD

**Issue by GrKoR** [esphome/aioesphomeapi#50]
https://github.com/esphome/aioesphomeapi/blob/9cfe8199f78c9ded90685a55245c86ea66c9a9a6/aioesphomeapi/api_pb2.py#L202

I'm GitHub newbie and I don't know if anyone will see my message [in the closed issue](https://github.com/esphome/aioesphomeapi/issues/34). So I made new one.

There is some discrepancy in the LOG_LEVEL constants of ESPHome and aioesphomeapi:

In ESPHome [core/log.h](https://github.com/esphome/esphome/blob/964ab654974ebb03ebd08949259fe4844537cd0c/esphome/core/log.h#L19)
```
#define ESPHOME_LOG_LEVEL_NONE 0
#define ESPHOME_LOG_LEVEL_ERROR 1
#define ESPHOME_LOG_LEVEL_WARN 2
#define ESPHOME_LOG_LEVEL_INFO 3
#define ESPHOME_LOG_LEVEL_CONFIG 4
#define ESPHOME_LOG_LEVEL_DEBUG 5
#define ESPHOME_LOG_LEVEL_VERBOSE 6
#define ESPHOME_LOG_LEVEL_VERY_VERBOSE 7
```

In aioesphomeapi [api_pb2.py](https://github.com/esphome/aioesphomeapi/blob/9cfe8199f78c9ded90685a55245c86ea66c9a9a6/aioesphomeapi/api_pb2.py#L202)
```
    ...
    _descriptor.EnumValueDescriptor(
      name='LOG_LEVEL_INFO', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOG_LEVEL_DEBUG', index=4, number=4,
      serialized_options=None,
      type=None),
    ...
```

From LOG_LEVEL_NONE to LOG_LEVEL_INFO all constants are the same.
From LOG_LEVEL_DEBUG to LOG_LEVEL_VERY_VERBOSE all constants are reduced by 1.

There is no LOG_LEVEL_CONFIG in aioesphomeapi and this is the reason for shifting constants by one and the incorrect work of subscribe_logs(log_callback, LOG_LEVEL_DEBUG).

**Comment by jesserockz** [comment]
@GrKoR Sorry abou that. You can always contest an issue being closed =).
I will close this and re-open your first one as I have had a look at the code and indeed this is a bug.
