### ISSUE TITLE
Add documentation and usage example

### ISSUE THREAD

**Issue by micw** [esphome/aioesphomeapi#7]
This library gibes powerful access to esphome devices. Unfortunately it lacks documentation or at least some examples how to get started.

As a good start, I found: https://gist.github.com/fpletz/d071c72e45d17ba274fd61ca7a465033

Created one to fetch images from esp32cam: https://gist.github.com/micw/202f9dee5c990f0b0f7e7c36b567d92b

**Comment by rs-development** [comment]
Is there absolutly no documentation? Is anything using the python library in production? I am tring to make a desicion between the native API and the HTTP API.

**Comment by IQNeoXen** [comment]
@glmnet could you merge #11 ? :) tyvm
