### ISSUE TITLE
Error while starting connection: [Errno 55] No buffer space available (SocketAPIError)

### ISSUE THREAD

**Issue by timmccor** [esphome/aioesphomeapi#801]
Hi,

Having updated to HomeAssistant 2023.12 (from 2023.11) and aioesphomeapi 19.2.1, I am no longer able to connect to the ESPHome device. The device remains accessible and is working correctly via the direct HTTP interface, but HomeAssistant can't connect to it. Instead it reports the following error:

2023-12-18 20:41:44.526 DEBUG (MainThread) [aioesphomeapi.reconnect_logic] Trying to connect to device @ x.x.x.x
2023-12-18 20:41:44.526 DEBUG (MainThread) [aioesphomeapi.reconnect_logic] Connected lock acquired for device @ x.x.x.x
2023-12-18 20:41:44.564 DEBUG (MainThread) [aioesphomeapi.connection] Cleaning up connection to device @ x.x.x.x
2023-12-18 20:41:44.564 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for device @ x.x.x.x: Error while starting connection: [Errno 55] No buffer space available (SocketAPIError)

Any suggestions gratefully received. I've tried the obvious stuff including rebooting both the HomeAssistant host and the ESPHome.

**Comment by bdraco** [comment]
Can you try manually removing this line?

https://github.com/esphome/aioesphomeapi/blob/6565d67c7372bbbc9f5c7037d6cd1edb9bfed568/aioesphomeapi/connection.py#L389

**Comment by timmccor** [comment]
Thanks for the suggestion. Commented out the line, but no change.

**Comment by bdraco** [comment]
You could add a logger line to get a full trace

```diff
diff --git a/aioesphomeapi/connection.py b/aioesphomeapi/connection.py
index 2a30bcd..8abe178 100644
--- a/aioesphomeapi/connection.py
+++ b/aioesphomeapi/connection.py
@@ -560,6 +560,7 @@ class APIConnection:
         except (Exception, CancelledError) as ex:
             # If the task was cancelled, we need to clean up the connection
             # and raise the CancelledError as APIConnectionError
+            _LOGGER.error("%s: Error starting connection: %s", self.log_name, ex, exc_info=True)
             self._cleanup()
             raise self._wrap_fatal_connection_exception("starting", ex)
         finally:
```

**Comment by timmccor** [comment]
Apologies @bdraco, when I went to enhance the logging I noticed that the changes to the Python weren't taking affect. I was directly editing the code in site-packages, and hadn't noticed it'd been compiled via Cython!

I can confirm that commenting out the setsockopt() call you suggested has worked.

What's the best way to fix this do you think? Catch the exception in setsockopt() and swallow it to allow it continue when it doesn't work? Alternatively could spit out an error suggesting the user increases their receive buffer size, or make it configurable in some way.

Happy to submit a PR.

**Comment by bdraco** [comment]
Great. Glad that is the issue as it makes it a lot more fixable

Can you figure out what the highest value your system will accept for the buffer size

If you can't figure out which system setting is limiting setting the buffer size, try decreasing the constant value BUFFER_SIZE until it works without error

**Comment by ryanwinter** [comment]
This also fixed my issue running on truenas core (freebsd), thanks!
