### ISSUE TITLE
More docs for the encryption based protocol? 

### ISSUE THREAD

**Issue by mathisloge** [esphome/aioesphomeapi#985]
Hey there, 

I'm currently developing https://github.com/mathisloge/cppesphome-api and was wondering if there is some more documentation then `https://esphome.io/components/api` ? 

Or do I have to analyse the aioesphomeapi source code to get a better understanding?

**Comment by bdraco** [comment]
Sorry there aren't any docs on this.  All the encryption code is in the _frame_helper.noise module
